cargo-features = ["codegen-backend"]

[workspace]
members = [
    "mazer-core",
    "mazer-cli",
    "mazer-macros",
    "mazer-data-structures", 
]
default-members = ["mazer-cli"]

resolver = "2"

[profile.dev]
debug = "full"
opt-level = 0
codegen-backend = "cranelift"

[profile.release]
codegen-units = 1
opt-level = "z"
panic = "abort"
strip = "symbols"
codegen-backend = "cranelift"
