cargo-features = ["codegen-backend"]

[workspace]
members = [
    "maple-core",
    "maple-cli",
    "maple-macros",
    "maple-data-structures", 
]
default-members = ["maple-cli"]

resolver = "2"

[profile.dev]
debug = 0
codegen-backend = "cranelift"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"
strip = "symbols"

