[package]
name = "maple-cli"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
maple-core = { path = "../maple-core" }

tokio = { version = "1.38.0", features = ["full"] }
warp = "0.3.7"

[[bin]]
name = "maple"
path = "src/main.rs"

