[package]
name = "mazer-cli"
version = "0.8.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clap = { version = "4.5.4", features = ["derive"] }
colored = "2.1.0"
mazer-core = { path = "../mazer-core" }
notify = "6.1.1"
opener = "0.7.1"
tokio = { version = "1.38.0", features = ["full"] }
warp = "0.3.7"

[[bin]]
name = "mazer"
path = "src/main.rs"
